# Building Predictive Models

In [2]:
import pandas as pd
import os
import numpy as np

### Import Data

In [3]:
# set the path of the processed data
processed_data_path = os.path.join(os.path.pardir,'data','processed')
train_file_path = os.path.join(processed_data_path, 'train.csv')
test_file_path = os.path.join(processed_data_path, 'test.csv')

In [4]:
train_df = pd.read_csv(train_file_path, index_col = 'PassengerId')
test_df = pd.read_csv(test_file_path, index_col = 'PassengerId')

In [5]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 33 columns):
Survived              891 non-null int64
Age                   891 non-null float64
Fare                  891 non-null float64
FamilySize            891 non-null int64
IsMother              891 non-null int64
IsMale                891 non-null int64
Deck_A                891 non-null int64
Deck_B                891 non-null int64
Deck_C                891 non-null int64
Deck_D                891 non-null int64
Deck_E                891 non-null int64
Deck_F                891 non-null int64
Deck_G                891 non-null int64
Deck_Z                891 non-null int64
Pclass_1              891 non-null int64
Pclass_2              891 non-null int64
Pclass_3              891 non-null int64
Title_Lady            891 non-null int64
Title_Master          891 non-null int64
Title_Miss            891 non-null int64
Title_Mr              891 non-null int64
Title_Mrs             891 non-

In [6]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 32 columns):
Age                   418 non-null float64
Fare                  418 non-null float64
FamilySize            418 non-null int64
IsMother              418 non-null int64
IsMale                418 non-null int64
Deck_A                418 non-null int64
Deck_B                418 non-null int64
Deck_C                418 non-null int64
Deck_D                418 non-null int64
Deck_E                418 non-null int64
Deck_F                418 non-null int64
Deck_G                418 non-null int64
Deck_Z                418 non-null int64
Pclass_1              418 non-null int64
Pclass_2              418 non-null int64
Pclass_3              418 non-null int64
Title_Lady            418 non-null int64
Title_Master          418 non-null int64
Title_Miss            418 non-null int64
Title_Mr              418 non-null int64
Title_Mrs             418 non-null int64
Title_Officer         418 n

### Data Preperation

In [7]:
X = train_df.loc[:,'Age':].values.astype('float') # standard practice capital letter 'X' is used for Matrix
y = train_df['Survived'].ravel() # standard practice small letter 'y' is used for Arrays

In [8]:
print X.shape, y.shape

(891L, 32L) (891L,)


In [9]:
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print X_train.shape, y_train.shape
print X_test.shape, y_test.shape

(712L, 32L) (712L,)
(179L, 32L) (179L,)


In [10]:
# average survival in train and test
print('mean survival in train:{0:.3f}'.format(np.mean(y_train)))
print('mean survival in test:{0:.3f}'.format(np.mean(y_test)))

mean survival in train:0.383
mean survival in test:0.385


#### Check Scikit-Learn Version

In [11]:
import sklearn

In [12]:
sklearn.__version__ # make sure you have version 0.19 or above to use DummyClassifier

'0.19.1'

### Baseline Model

In [13]:
# import function
from sklearn.dummy import DummyClassifier

In [14]:
# create model
model_dummy = DummyClassifier(strategy='most_frequent', random_state=0)

In [15]:
# train model
model_dummy.fit(X_train, y_train)

DummyClassifier(constant=None, random_state=0, strategy='most_frequent')

In [16]:
print('score for baseline model : {0:.2f}'.format(model_dummy.score(X_test, y_test)))

score for baseline model : 0.61


In [17]:
# performance metrics
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [18]:
# accuracy score
print('Accuracy for baseline model : {0:.2f}'.format(accuracy_score(y_test, model_dummy.predict(X_test))))

Accuracy for baseline model : 0.61


In [19]:
# confusion matrix
print('Confusion matrix for baseline model : \n {0}'.format(confusion_matrix(y_test, model_dummy.predict(X_test))))

Confusion matrix for baseline model : 
 [[110   0]
 [ 69   0]]


In [20]:
# precision and recall score
print('Precision score for baseline model : {0:.2f}'.format(precision_score(y_test, model_dummy.predict(X_test))))
print('Recall score for baseline model : {0:.2f}'.format(recall_score(y_test, model_dummy.predict(X_test))))

Precision score for baseline model : 0.00
Recall score for baseline model : 0.00


C:\Users\Utkarsh\Anaconda2\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


### First Kaggle Submission

In [21]:
# converting to the matrix
test_X = test_df.values.astype('float')

In [22]:
# get predections
predictions = model_dummy.predict(test_X)

In [23]:
df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived': predictions})

In [24]:
df_submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [25]:
submission_data_path = os.path.join(os.path.pardir, 'data', 'external')
submission_file_path = os.path.join(os.path.pardir, '01_dummy.csv')

In [26]:
df_submission.to_csv(submission_file_path, index=False)

In [27]:
def get_submission_file(model, filename):
    # converting to the matrix
    test_X = test_df.values.astype('float')
    # make predections
    predictions = model.predict(test_X)
    # submit dataframe
    df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived': predictions})
    # submission file
    submission_data_path = os.path.join(os.path.pardir, 'data', 'external')
    submission_file_path = os.path.join(submission_data_path, filename)    
    # write to the file
    df_submission.to_csv(submission_file_path, index=False)
    

In [57]:
# get submission file
get_submission_file(model_dummy, '01_dummy.csv')

### Logistic Regression Model

In [28]:
# import function
from sklearn.linear_model import LogisticRegression

In [29]:
# create model
model_lr_1 = LogisticRegression(random_state=0)

In [30]:
# train model
model_lr_1.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [31]:
# evaluate model
print('score for logestic regration - version 1: {0:2f}'.format(model_lr_1.score(X_test, y_test)))

score for logestic regration - version 1: 0.832402


In [32]:
# performance metrics
# accuracy
print('Accuracy for baseline model : {0:.2f}'.format(accuracy_score(y_test, model_lr_1.predict(X_test))))
# confusion matrix
print('Confusion matrix for baseline model : \n {0}'.format(confusion_matrix(y_test, model_lr_1.predict(X_test))))
# precision
print('Precision score for baseline model : {0:.2f}'.format(precision_score(y_test, model_lr_1.predict(X_test))))
# recall
print('Recall score for baseline model : {0:.2f}'.format(recall_score(y_test, model_lr_1.predict(X_test))))

Accuracy for baseline model : 0.83
Confusion matrix for baseline model : 
 [[95 15]
 [15 54]]
Precision score for baseline model : 0.78
Recall score for baseline model : 0.78


In [33]:
# model cofficients
model_lr_1.coef_

array([[-0.0284227 ,  0.00455451, -0.50009091,  0.61781314, -0.8139233 ,
         0.12845079, -0.1728179 , -0.39317833,  0.52159976,  1.09941224,
         0.40341217, -0.18345051, -0.30036041,  0.96533486,  0.48256743,
        -0.34483447,  0.28089591,  1.21761326,  0.56363966, -1.44586303,
         1.07245555, -0.11273706, -0.47293647,  0.16255645,  0.24716927,
         0.28009442,  0.41324768,  0.49183529,  0.46198829,  0.14924424,
         0.37283518,  0.73023264]])

### Second Kaggle Submission

In [64]:
# get submission file
get_submission_file(model_lr_1, '02_lr.csv')

## Part 2

### Hyperparameter Optimization

In [34]:
# base model
model_lr = LogisticRegression()

In [35]:
from sklearn.model_selection import GridSearchCV

In [36]:
parameters = { 'C':[1.0,10.0,50.0,100.0,1000.0], 'penalty':['l1', 'l2']}
clf = GridSearchCV(model_lr, param_grid = parameters, cv=3)

In [37]:
clf.fit(X_train,y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'penalty': ['l1', 'l2'], 'C': [1.0, 10.0, 50.0, 100.0, 1000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [38]:
clf.best_params_

{'C': 1.0, 'penalty': 'l1'}

In [39]:
print('best score : {0:.2f}'.format(clf.best_score_))

best score : 0.83


In [40]:
# evaluate model
print('best score for logistic regression - version 2 : {0:.2f}'.format(clf.score(X_test, y_test)))

best score for logistic regression - version 2 : 0.83


### Making Third Submission

In [72]:
# get submission file
get_submission_file(clf, '03_lr.csv')

## Feature Normalization and Standardization

In [41]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

### Feature Normalization

In [42]:
# feature normalization
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [43]:
X_train_scaled[:,0].min(),X_train_scaled[:,0].max()

(0.0, 1.0)

In [44]:
# normalise test data
X_train_scaled = scaler.transform(X_test)

### Feature Standardization

In [45]:
 # feature standardization
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

#### Create Model after Standardization

In [46]:
# base model
model_lr = LogisticRegression()
parameters = { 'C':[1.0,10.0,50.0,100.0,1000.0], 'penalty':['l1', 'l2']}
clf = GridSearchCV(model_lr, param_grid = parameters, cv=3)
clf.fit(X_train_scaled,y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'penalty': ['l1', 'l2'], 'C': [1.0, 10.0, 50.0, 100.0, 1000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [47]:
clf.best_score_

0.8132022471910112

In [48]:
print('best score for logistic regression - version 2 : {0:.2f}'.format(clf.score(X_test_scaled, y_test)))

best score for logistic regression - version 2 : 0.82


### Model Persistance

In [49]:
# import pickle library
import pickle

In [50]:
# create the file path
model_file_path = os.path.join(os.path.pardir,'models','lr_model.pkl')
scaler_file_path = os.path.join(os.path.pardir, 'models','lr_scaler.pkl')

In [51]:
# open the files to write
model_file_pickle = open(model_file_path, 'wb')
scaler_file_pickle = open(scaler_file_path, 'wb')

In [52]:
# persist the model and scaler
pickle.dump(clf,model_file_pickle)
pickle.dump(scaler,scaler_file_pickle)

In [53]:
# close the file
model_file_pickle.close()
scaler_file_pickle.close()

#### load the persisted file

In [54]:
# open file in read mode
model_file_pickle = open(model_file_path, 'r')
scaler_file_pickle = open(scaler_file_path, 'r')
# load files
clf_loaded = pickle.load(model_file_pickle)
scaler_loaded = pickle.load(scaler_file_pickle) #calculate
# close files
model_file_pickle.close()
scaler_file_pickle.close()

In [55]:
clf_loaded

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'penalty': ['l1', 'l2'], 'C': [1.0, 10.0, 50.0, 100.0, 1000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [56]:
scaler_loaded

StandardScaler(copy=True, with_mean=True, with_std=True)

In [64]:
# transform the test data using loaded scaler object
X_test_scaled = scaler_loaded.transform(X_test)
# calculate the score using loaded model object
print('best score for peristed logistic regression : {0:.2f}'.format(clf_loaded.score(X_test_scaled, y_test)))

best score for peristed logistic regression : 0.82


In [69]:
model.oob_prediction_

array([0.52609926, 0.28564044, 0.11637101, 0.2445124 , 0.04923931,
       0.30858804, 0.09538301, 0.90484695, 0.05859263, 0.23750786,
       0.99231094, 0.47423796, 0.30969766, 0.79940029, 0.85665007,
       0.20996496, 0.22284738, 0.0479782 , 0.81333804, 0.40376839,
       0.02831361, 0.225614  , 0.38194003, 0.04057188, 0.55276264,
       0.24577002, 0.1254097 , 0.59065677, 0.26407224, 0.87921311,
       0.11953085, 0.24735053, 0.55941638, 0.12292592, 0.77490666,
       0.11083723, 0.11524633, 0.19689112, 0.80041137, 0.18130739,
       0.99983333, 0.1196078 , 0.52070347, 0.76731373, 0.0161689 ,
       0.22754292, 0.02084229, 0.05118995, 0.65249546, 0.1293803 ,
       0.05592356, 0.11981069, 0.98844062, 0.30130621, 0.49449677,
       0.36554712, 0.01053391, 0.86932858, 0.98594473, 0.77530255,
       0.04490137, 0.13724846, 0.98226813, 0.42752201, 0.13938399,
       0.99861224, 0.81073576, 0.79488581, 0.01570454, 0.04298679,
       0.4025493 , 0.01897539, 0.06411786, 0.38235162, 0.06657

In [ ]:
print('best score for logistic regression - version 2 : {0:.2f}'.format(clf.score(X_test_scaled, y_test)))